from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)

from reportlab.lib.styles import getSampleStyleSheet


styles = getSampleStyleSheet()


def generate_report(
    ats_score,
    skill_score,
    semantic_score,
    matched_skills,
    missing_skills
):

    pdf = SimpleDocTemplate("ats_report.pdf")

    story = []

    title = Paragraph(
        "<b><font size=18>AI Resume Screening Report</font></b>",
        styles["Title"]
    )

    story.append(title)
    story.append(Spacer(1,20))

    story.append(
        Paragraph(
            f"<b>ATS Score:</b> {ats_score*100:.1f}%",
            styles["Heading2"]
        )
    )

    story.append(
        Paragraph(
            f"<b>Skill Match:</b> {skill_score*100:.1f}%",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph(
            f"<b>Semantic Match:</b> {semantic_score*100:.1f}%",
            styles["Normal"]
        )
    )

    story.append(Spacer(1,20))

    if ats_score >= 0.85:
        verdict = "Excellent Match"

    elif ats_score >= 0.70:
        verdict = "Good Match"

    elif ats_score >= 0.50:
        verdict = "Average Match"

    else:
        verdict = "Poor Match"

    story.append(
        Paragraph(
            f"<b>Overall Verdict:</b> {verdict}",
            styles["Heading2"]
        )
    )

    story.append(Spacer(1,20))

    story.append(
        Paragraph(
            "<b>Matched Skills</b>",
            styles["Heading2"]
        )
    )

    for skill in matched_skills:

        story.append(
            Paragraph(
                f"✓ {skill}",
                styles["Normal"]
            )
        )

    story.append(Spacer(1,20))

    story.append(
        Paragraph(
            "<b>Missing Skills</b>",
            styles["Heading2"]
        )
    )

    for skill in missing_skills:

        story.append(
            Paragraph(
                f"✗ {skill}",
                styles["Normal"]
            )
        )

    story.append(Spacer(1,20))

    feedback = "The candidate demonstrates "

    if ats_score >= 0.85:

        feedback += (
            "excellent alignment with the job description. "
            "The resume contains most required skills and is highly suitable for this role."
        )

    elif ats_score >= 0.70:

        feedback += (
            "good alignment with the job requirements. "
            "Adding the missing skills would further improve ATS compatibility."
        )

    elif ats_score >= 0.50:

        feedback += (
            "partial alignment with the role. "
            "The candidate should strengthen the missing technical skills."
        )

    else:

        feedback += (
            "limited alignment with the current job requirements. "
            "Significant upskilling is recommended before applying."
        )

    story.append(
        Paragraph(
            "<b>Recruiter Feedback</b>",
            styles["Heading2"]
        )
    )

    story.append(
        Paragraph(
            feedback,
            styles["BodyText"]
        )
    )

    story.append(Spacer(1,30))

    story.append(
        Paragraph(
            "<i>Generated by AI Resume Screening System</i>",
            styles["Italic"]
        )
    )

    pdf.build(story)

    return "ats_report.pdf"